variables:
  python.version: '3.9'

jobs:
- job: UpdateBuildNumber
  timeoutInMinutes: 5
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)
        architecture: x64
    - script: python version.py
    - bash: echo "##vso[build.UpdateBuildNumber]`cat version`"

- job: Windows
  pool:
    vmImage: windows-latest
  steps:
    - template: cross-platform-build.yml

- job: MacOS
  pool:
    vmImage: macos-latest
  steps:
    - template: cross-platform-build.yml