variables:
  python.version: '3.9'

jobs:
- job: UpdateBuildNumber
  timeoutInMinutes: 5
  pool:
    vmImage: ubuntu-latest

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(python.version)
        architecture: x64
    - script: python version.py
    - bash: echo "##vso[build.UpdateBuildNumber]`cat version`"

- job: Windows
  dependsOn: UpdateBuildNumber
  timeoutInMinutes: 15
  strategy:
    maxParallel: 2
    matrix:
      x64:
        poolName: Azure Pipelines
        vmImage: windows-latest
        buildArch: x64
  pool:
    name: $(poolName)
    vmImage: $(vmImage)
  steps:
    - template: cross-platform-build.yml

- job: MacOS
  timeoutInMinutes: 15
  dependsOn: UpdateBuildNumber
  strategy:
    maxParallel: 2
    matrix:
      x64:
        poolName: Azure Pipelines
        vmImage: macos-latest
        buildArch: x64
      arm64:
        poolName: M1 Mac
        vmImage:
        buildArch: arm64
  pool:
    name: $(poolName)
    vmImage: $(vmImage)
  steps:
    - template: cross-platform-build.yml