
jobs:
- job: Windows
  pool:
    vmImage: windows-latest
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
        architecture: 'x64'

    - script: python -m pip install --upgrade pip && pip install -r requirements.txt
      displayName: 'Install dependencies'
    
    - script: |
        pyinstaller -y demo.spec
      displayName: 'Build pyInstaller Application'
    
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
        archiveFile: '$(Build.SourcesDirectory)/dist.zip'
    
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'pros_cli-$(Build.BuildNumber)-macos-$(buildArch)'
        targetPath: 'out'